# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Pass - Sponsorship(876b9fe0-62f2-4493-8fa9-195476c375e7)'
    subscriptionId: '876b9fe0-62f2-4493-8fa9-195476c375e7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'akslab'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'AzureResourceGroup2/WindowsVirtualMachineScaleSet.json'
    deploymentMode: 'Incremental'
